[package]
name = "graph_matrix"
version = "0.1.0"
authors = ["Seth Bromberger <github@bromberger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
itertools-num = "0.1.3"
